-- 1.How do transactions change through time? Revenue by month, number of transactions and monthly growth.

SELECT
	period,
    total_trans,
    revenue,
	ROUND((revenue / LAG(revenue) OVER(ORDER BY period)-1)*100,2) AS growth_pct	
FROM
	( 
	 SELECT
		CONCAT(year, "-" ,LPAD(month,2,"0")) AS period, 
		COUNT(id) AS total_trans,
		ROUND(SUM(amount),2) AS revenue 
	 FROM trans_clean
	 GROUP BY period
	 ORDER BY period) AS a;
        
-- 2. Which clients spend the most throughout their lifetime? Top 10 clients and their contribution to total revenue.

SELECT 
	ranking,
    person,
    total_spent,
    total_contribution_pct
FROM
	(SELECT
		RANK() OVER(ORDER BY a.total_spent DESC) AS ranking,
		b.person,
		a.total_spent,
		ROUND(100 * a.total_spent / SUM(a.total_spent) OVER(),2) AS total_contribution_pct
	FROM
		(SELECT 
			User_id,
			ROUND(SUM(amount),2) AS total_spent
		FROM trans_clean
		GROUP BY user_id) a
	JOIN users b ON b.user_id = a.user_id) aa
WHERE ranking <=10
ORDER BY ranking;

-- 3. How much revenue is generated by the top spending customers?

SELECT
	ROUND(100 * SUM(CASE WHEN spending_cume_dist >=0.99 THEN total_spent ELSE 0 END) 
			/ SUM(total_spent), 2) AS top1contribution,
	ROUND(100 * SUM(CASE WHEN spending_cume_dist >=0.95 THEN total_spent ELSE 0 END) 
			/ SUM(total_spent), 2) AS top5contribution,
	ROUND(100 * SUM(CASE WHEN spending_cume_dist >=0.90 THEN total_spent ELSE 0 END) 
			/ SUM(total_spent), 2) AS top10contribution,
	ROUND(100 * SUM(CASE WHEN spending_cume_dist >=0.80 THEN total_spent ELSE 0 END) 
			/ SUM(total_spent), 2) AS top20contribution
FROM
	(SELECT
		user_id,
		total_spent,
		CUME_DIST() OVER(ORDER BY total_spent) AS spending_cume_dist
	FROM
		(SELECT 
			User_id,
			SUM(amount) AS total_spent
		FROM trans_clean
		GROUP BY user_id) a) aa;

-- 4. How does average yearly spending vary across income groups?

SELECT
	income_quartile,
	ROUND(AVG(yearly_spent),2) AS avg_yearly_spending
FROM
	(SELECT
			a.user_id,
			NTILE(4) OVER(ORDER BY b.yearly_income) AS income_quartile,
			yearly_spent
		FROM
			(SELECT
				user_id,
				year,
				SUM(amount) AS yearly_spent
			FROM trans_clean
			GROUP BY user_id,year) a
	JOIN users_clean b ON a.user_id = b.user_id) aa
GROUP BY income_quartile
ORDER BY income_quartile;

-- 5. How do spending patterns differ across card types?

SELECT
	Card_type,
    num_trans, 
    avg_trans,
    total_rev,
    ROUND(100 * total_rev / SUM(total_rev) OVER(),2) AS contribution
FROM
    (SELECT 
		b.Card_type,
		COUNT(a.id) AS num_trans,
		ROUND(AVG(a.amount),2) AS avg_trans,
		ROUND(SUM(a.amount),2) AS total_rev
	FROM trans_clean a
	JOIN cards_clean b ON a.User_id = b.user_id AND a.card_id = b.Card_index
	GROUP BY b.card_type
	ORDER BY total_rev) a;

-- 6. How does transaction size vary across different credit limit groups?

SELECT 
	percentile AS percentile_by_limit,
    ROUND(AVG(credit_limit),2) AS avg_credit_limit,
    ROUND(AVG(amount),2) AS avg_trans_size
FROM
	(SELECT 
		b.credit_limit,
		NTILE(4) OVER(ORDER BY b.Credit_limit) AS percentile,
		a.amount
	FROM trans_clean a
	JOIN cards_clean b ON a.User_id = b.user_id AND a.card_id = b.Card_index) a
GROUP BY percentile_by_limit
ORDER BY percentile_by_limit DESC;

-- 7. Which clients have unusual spending?

WITH client_spending AS (
    SELECT
        b.user_id,
        percentile AS percentile_year_income,
        ROUND(SUM(amount),2) AS total_client
    FROM trans_clean b
    JOIN (
        SELECT
            user_id,
            NTILE(4) OVER(ORDER BY yearly_income) AS percentile
        FROM users_clean
    ) a
        ON a.user_id = b.user_id
    GROUP BY b.user_id
),

client_stats AS (
    SELECT
        user_id,
        percentile_year_income,
        total_client,
        ROUND(AVG(total_client) OVER(PARTITION BY percentile_year_income),2) AS group_mean_spent,
        ROUND(STDDEV(total_client) OVER(PARTITION BY percentile_year_income),2) AS stdev
    FROM client_spending
)

SELECT
    user_id,
    percentile_year_income,
    total_client,
    group_mean_spent,
    stdev,
    ROUND((total_client - group_mean_spent) / stdev, 2) AS z_score
FROM client_stats
ORDER BY ABS(z_score) DESC;

-- 8. How does customer spending evolve after acquisition? (Cohort Analysis)

WITH customer_yearly_spending  AS(
	SELECT
		a.user_id,
		b.first_trans AS cohort,
		year - b.first_trans AS cohort_age,
		SUM(amount) AS yearly_spent
	FROM trans_clean a
	JOIN
		(SELECT 
				user_id,
				MIN(year) AS first_trans    
			FROM trans_clean
			GROUP BY user_id) b
	ON a.user_id = b.user_id
	GROUP BY 
		user_id,
		b.first_trans,
        year
),
cohort_metrics AS(
	SELECT
		cohort,
		cohort_age,
		ROUND(AVG(yearly_spent),2) AS avg_yearly_spending
	FROM customer_yearly_spending
	GROUP BY cohort, cohort_age
)
SELECT
	cohort,
    cohort_age,
    avg_yearly_spending,
    ROUND(
		(avg_yearly_spending /
        FIRST_VALUE(avg_yearly_spending) OVER(PARTITION BY cohort ORDER BY cohort_age)-1)*100
        ,2) AS rev_growth_vs_year0
FROM cohort_metrics;
